Issue #52:Bug, analyzing curl exit code

diff --git a/src/zmbkpose b/src/zmbkpose
--- a/src/zmbkpose
+++ b/src/zmbkpose
@@ -315,15 +315,15 @@ function zimbra_mailbox_backup()
 
 	#Because sporadic ssl error, we will try several times. See issues 35.
 	for i in 1 2 3 4;do
-		if ! $CURL_cmd $CURL_args -u $ADMINUSER:$ADMINPASS -o "$backup_file" \
-			"https://$mailhost:7071/home/$mailbox/?fmt=tgz$search_query" ;then
-			case $? in 
-				35) debug "Retry $i to https://$mailhost:7071 by SSL error";continue ;; 
-				*) return 1;; #Another errors
-			esac
-		fi
-		return 0
+		ret=0; $CURL_cmd $CURL_args -u $ADMINUSER:$ADMINPASS -o "$backup_file" \
+			"https://$mailhost:7071/home/$mailbox/?fmt=tgz$search_query" || ret=$?
+		case $ret in 
+			35) debug "Try $i to https://$mailhost:7071 failed by SSL error";; 
+			0) return 0;;
+			*) debug "Curl exiting with error code $ret"; return 1;;
+		esac
 	done
+	error "Backup failed after several attempts"
 	return 1
 }
 
